apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-web
  template:
    metadata:
      labels:
        app: ocr-web
    spec:
      containers:
        - name: ocr-web
          image: benhorv/ocr-web:{{ .Values.env.WEB_VERSION }}
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ocr-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-worker
  template:
    metadata:
      labels:
        app: ocr-worker
    spec:
      containers:
        - name: ocr-worker
          image: benhorv/ocr-worker:{{ .Values.env.WORKER_VERSION }}
          env:
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ocr-data
